project:
  type: book
  output-dir: docs

book:
  title: "RM1"
  author: "Armando Teixeira-Pinto"
  date: "12/5/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  downloads: [pdf, epub]

bibliography: references.bib

format:
  html:
    theme: darkly
    code-fold: true
    code-summary: "Show the code"
  pdf:
    documentclass: scrreprt

editor: visual

